# Generated by Django 3.0.5 on 2020-04-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('author', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
