# Generated by Django 3.0 on 2020-05-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/avatars/avatar.png', upload_to='images/avatars'),
        ),
    ]
